### PR TITLE
Two fixes: bring back support for no callback specified, fix modems with no +CLAC support

### PR DESCRIPTION
**Pull request by bennyslbs**
I have fixed it at least for my usecase:
Sending and receiving SMSes with/without getting SMS Status reports (failed without grapping the status report)
It is working on SIM800L, don't support +CLAC.

### CODE REVIEW

**Comment by bennyslbs** [comment]
@babca 
This is the wrong place to write this, but there is no Issus tab on your fork of python-gsmmodem, I don't know if it is an error or it is the intension that the origin should be used.

* You have not tagged version 0.10
* Sending a SMS takes much longer time (12-18 seconds) at my SIM800L. Prior it took around 5 seconds using my branch (sim800l and my main until I merged your changes).

**Comment by babca** [comment]
Thank you for the suggestion! I've added the Issues tab and v0.10 pre-release. Yeah I also feel the merge introduced new bugs. I can see some timeouts when sending long sms in specific cases on my Huawei USB modem. I'm going to test it commit by commit to find out which one introduce the issue. I have no SIM800/SIM900 hardware, so I'm not able to test that.

**Comment by bennyslbs** [comment]
To debug on why it takes longer time you can change logging to include DEBUG and append messages with timestamp.
Example: logging.basicConfig(format='%(asctime)s %(levelname)s: %(message)s', level=logging.DEBUG)

As example:
I have done that in last commit of my [smsgw](https://github.com/bennyslbs/smsgw) wrapper SMS Gateway (can also send via other methods than modem), except loglevel=WARNING.

For the SIM800L I can't find any single point taking much time, but seems as there is a delay after the SMS have been sent to it is finished.

From the log output it seems as it is waiting for the SMS Status report, even if I don't use it, but I will accept it as it is for now.

**Comment by babca** [comment]
I think b1825d8bf1ccf0bab15006b26ff5c9a3c8c20fc5 is now not needed. Changes from paolo-losi (4ce4081531b16a62dbd365b09b442b0cfac254c0) also include checks if a callback is set before even calling it. It's possible that his changes are not implemented correctly or he forgot to edit the code somewhere. What do you think? If you still think it is necessary to include let me know.

**Comment by bennyslbs** [comment]
Hi @babca 
_handleSmsStatusReportTe (function I have created prior to the merge) uses smsStatusReportCallback in the last line without check.

I have just checked the code, and I think it is the only location where the _placeholderCallback can be called from are from self.incomingCallCallback calls and in my function.

I think the way with the _placeholderCallback gives that less checks are needed in the code. Further it gives easy access to place a debug message in that function to see when a function is "missing".

In change from paolo-losi (4ce4081) _placeholderCallback is used in line 136, but method have been removed.

Br,
Benny

**Comment by babca** [comment]
I see. I haven't noticed a use of callback in `_handleSmsStatusReportTe()`. Ok let's put the dummy function back.

**Pull request merged**
