### PR TITLE
Add an option in sendsms.py to prevent concurrent modem access

### PR DESCRIPTION
**Pull request by tahajahangir**

### CODE REVIEW

**Comment by tahajahangir** [comment]
Rebased to master

**Comment by babca** [comment]
Thank you for the pull request. 

The only library `python-gsmmodem` relies on right now is `pyserial`.

I'm not sure if it is a good idea to make the library dependent on another library.
Is there any more lightweight solution for this?

Does anyone know `oslo.concurrency`?

**Comment by tahajahangir** [comment]
I didn't add any (hard) dependency to library. The `oslo.concurrency` package is only imported when `--lock-path` option is used.

The `oslo.concurrency` package is part of openstack project and is actively maintained. It supersedes the [lockfile](https://pypi.python.org/pypi/lockfile/) package.

**Comment by babca** [comment]
Ok, let's merge it. It seems it's failing with Python 3.5, are you able to fix it first?

**Comment by tahajahangir** [comment]
The `sendsms.py` script is using `raw_input` function which is not compatible with python3. (the problem is not related to this pull request)

I tested with python3.6 with passing message as argument (as follows) and it's OK.

    sendsms.py -i /dev/ttyUSB1 -l /tmp/smslock "<number>" "<message>"

**Comment by tomchy** [comment]
I am not sure, but I remember that there was one "unstable" unit test, that failed around first minute and reported some timeout inside write operation. It stopped failing so I thought that the problem is solved...

@babca: Could you try rerunning Travis build and paste failed job log (I do not know, but I cannot fetch it)?

**Comment by babca** [comment]
I reran it several times already. I took a closer look at it and it is failing on "--use-mirrors". Travis still uses the old `.travis.yml` settings. We probably have to make a new PR.

**Comment by babca** [comment]
>  To apply upstream changes for travis configuration one has to add commit to PR or to close / reopen it.

[source](http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit/17624403#17624403)

**Comment by tahajahangir** [comment]
Thanks 💐

**Pull request merged**
