### PR TITLE
Getting an SMS index/SMS deletion

### PR DESCRIPTION
**Pull request by malanovo**
Fix for issue #51, which was also affecting my environment.  This modifies the ReceivedSms class so that there's access to the message index, which makes it possible to call things like deleteStoredSms without having to guess at the index.

### CODE REVIEW

**Comment by malanovo** [comment]
Is there something weird with the Travis environment?  All the tests pass when I run them in my environment, and the changes I submitted are pretty minor, so I can't see why Travis would have errored out like it did.

**Comment by babca** [comment]
First, thank for the PR! Second, I found a bug (code inconsistencies) caused from merging all the forks into this one and I tried to fix it back in November, but I got Travis CI broken. I need to revert last 3 commits in master and start again :-) I just haven't a free time to do this yet. I think I can revert the commits and merge your PR, and try to fix the bug later.

**Comment by malanovo** [comment]
Thanks for the followup, I can understand the lack of free time.  If there's anything I can do to help, please let me know.

**Comment by babca** [comment]
I rerun the tests and all passed. It was apparently a bug in Travis.

**Pull request merged**
